# programフォルダ内の起動ファイルを読み込む
from program import talk_child
from program import talk_parent
from program import GraphDraw_likelihood_distribution
from program import GraphDraw_belief_hiddenstate_distribution
from program import GraphDraw_belief_conditional_hiddenstate_distribution
from program import talk_parent_known